---
# -----------------------------------------------------------------------------------------------------------
# CI Sim campaign settings
# -----------------------------------------------------------------------------------------------------------
# This file contains parameters for the CI SIL simulation campaigns.
# list of sil batches to run
sil_campaign:
     sil_set_1:
          num_sims: 1 # 100
          runtime: 30 # [seconds] how long the FSW is allowed to run
          outfile: "sil_logs.log"
          fsw_percent_to_log: 0.01 # fraction of FSW data to log for plotting
          param_changes:
               MAX_TIME: 9000 # 96000 # [s]
          description: "Baseline simulation campaign with nominal parameters."
     sil_set_2:
          num_sims: 2 # 50
          runtime: 15 # [seconds] how long the FSW is allowed to run
          outfile: "sil_logs.log"
          fsw_percent_to_log: 0.01 # fraction of FSW data to log for plotting
          param_changes:
               MAX_TIME: 3600 # 96000 # [s]
               magnetorquers:
                    random_failures: true
                    N_rand_failures: 1
          description: "Single point failure magnetorquer simulation campaign."